version: '3.4'

networks:
  guohc_net:
    external: true

services:
  mircroService:
    image: medical:1.0
    container_name: medicalApplication
    ports:
      - "8080:8080"
    volumes:
      - /opt/docker/medical/data:/data
    networks:
      - guohc_net
    depends_on:
      - redis6381
      - redis6382
      - redis6383
      - redis6384
      - redis6385
      - redis6386
      - mysql

  redis6381:
    image: redis
    container_name: redis6381
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6381/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6381/data:/data
    networks:
      - guohc_net
    ports:
      - "6381:6381"
      - "16381:16381"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis6382:
    image: redis
    container_name: redis6382
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6382/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6382/data:/data
    networks:
      - guohc_net
    ports:
      - "6382:6382"
      - "16382:16382"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis6383:
    image: redis
    container_name: redis6383
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6383/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6383/data:/data
    networks:
      - guohc_net
    ports:
      - "6383:6383"
      - "16383:16383"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis6384:
    image: redis
    container_name: redis6384
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6384/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6384/data:/data
    networks:
      - guohc_net
    ports:
      - "6384:6384"
      - "16384:16384"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis6385:
    image: redis
    container_name: redis6385
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6385/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6385/data:/data
    networks:
      - guohc_net
    ports:
      - "6385:6385"
      - "16385:16385"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis6386:
    image: redis
    container_name: redis6386
    command:
      ["redis-server", "/etc/redis.conf"]
    volumes:
      - /opt/docker/redis-cluster/redis-6386/conf/redis.conf:/etc/redis.conf
      - /opt/docker/redis-cluster/redis-6386/data:/data
    networks:
      - guohc_net
    ports:
      - "6386:6386"
      - "16386:16386"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=442520"
      - "MYSQL_DATABASE=media"
      - "TZ=Asia/Shanghai"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/mysql/conf:/etc/mysql/conf.d
      - /opt/docker/mysql/db:/var/lib/mysql
      - /opt/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - guohc_net
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/media.sql